
on:
  push:
    branches: [main, master]
  pull_request:

name: Deploy TROCA shiny app

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    concurrency:
      group: pr-${{ github.event.pull_request.number || github.run_id }}
      cancel-in-progress: true

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Install packages
        run: |
          Rscript -e 'install.packages("pak")'
          Rscript -e 'pak::pkg_install(c("renv", "here", "rsconnect"))'

      - name: Install troca from branch
        if: github.event_name == 'pull_request'
        run: |
          BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF##*/}}
          echo "Current branch: $BRANCH_NAME"
          Rscript -e "pak::pkg_install('oxford-pharmacoepi/troca@$BRANCH_NAME')"

      - name: install troca from main
        if: github.event_name != 'pull_request'
        run: |
          Rscript -e 'pak::pkg_install("oxford-pharmacoepi/troca")'

      - name: Create renv file
        run: Rscript -e 'renv::init()'
        working-directory: extras/shiny/

      - name: Deploy to shinyapps.io
        if: github.event_name != 'pull_request'
        env:
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: Rscript extras/deployShiny.R
