on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up R and cache base packages
        uses: rstudio/shiny-workflows/setup-r-package@v1
        with:
          packages: |
            renv
            sessioninfo
            pak
          cache-version: v1  # Change this to invalidate cache manually

      - name: Install project-specific R dependencies
        shell: Rscript {0}
        run: |
          deps <- unique(renv::dependencies()$Package)
          message("Installing dependencies: ", paste(deps, collapse = ", "))
          pak::pak(deps, upgrade = FALSE)

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto website
        run: quarto render

      - name: Publish
        if: github.event_name != 'pull_request'
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
          publish_dir: ./_site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
